# Generated by Django 4.0.5 on 2022-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=100)),
                ('CourseNumber', models.IntegerField(default=0)),
                ('InstructorName', models.CharField(blank=True, default='', max_length=100)),
                ('Duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
            ],
        ),
    ]
